# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

variables:
  - group: mebs-pipieline-secrets

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      curl https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip -o terraform_1.0.7_linux_amd64.zip
      unzip terraform_1.0.7_linux_amd64.zip
      mv terraform /usr/local/bin/
      terraform -help
    displayName: 'Install Terraform'
  - script: |
      export DATABASE_URL=$(heroku config:get DATABASE_URL --app mebs-infrastructure-backend)
      terraform init -backend-config="conn_str=$DATABASE_URL"
    displayName: Terraform Init
    env:
      HEROKU_API_KEY: $(HEROKU_API_KEY)
      HEROKU_EMAIL: $(HEROKU_EMAIL)
